package discover

func builtinMiniList() []string {
	return []string{
		"/api", "/api/", "/api/v1", "/api/v2", "/api/v3", "/v1", "/v2", "/v3",
		"/api/v1/", "/api/v2/", "/api/v3/",
		"/openapi.json", "/openapi.yaml", "/swagger.json", "/swagger.yaml",
		"/swagger", "/swagger/", "/swagger/index.html", "/swagger-ui",
		"/swagger-ui/", "/swagger-ui.html", "/v3/api-docs", "/v2/api-docs",
		"/api-docs", "/api-docs/", "/docs", "/docs/", "/redoc", "/redoc/",
		"/graphql", "/graphiql", "/api/graphql", "/v1/graphql", "/query",
		"/playground", "/altair",
		"/health", "/healthz", "/ready", "/readyz", "/status", "/ping",
		"/metrics", "/actuator", "/actuator/health", "/actuator/env",
		"/actuator/mappings", "/actuator/info", "/actuator/heapdump",
		"/.well-known/openid-configuration", "/.well-known/jwks.json",
		"/oauth/token", "/oauth/authorize", "/oauth2/token",
		"/login", "/logout", "/register", "/signup", "/auth", "/auth/login",
		"/api/auth", "/api/login", "/api/register", "/api/users", "/api/user",
		"/api/me", "/api/admin", "/api/account",
		"/api/v1/users", "/api/v1/user", "/api/v1/me", "/api/v1/login",
		"/api/v1/auth", "/api/v1/admin", "/api/v1/account", "/api/v1/health",
		"/api/v2/users", "/api/v2/user", "/api/v2/me", "/api/v2/login",
		"/api/v2/auth", "/api/v2/admin", "/api/v2/account",
		"/api/v2/resources", "/api/v2/resources/",
		"/api/v1/resources", "/api/resources",
		"/api/books", "/api/products", "/api/orders", "/api/items",
		"/api/posts", "/api/comments", "/api/files", "/api/upload",
		"/api/search", "/api/config",
		"/wp-json", "/wp-json/wp/v2", "/wp-json/wp/v2/users",
		"/rest", "/rest/", "/rest/v1", "/rest/v2",
		"/services", "/Services", "/ws", "/soap", "/?wsdl", "/service?wsdl",
		"/console", "/admin", "/admin/", "/admin/api", "/manage",
		"/debug", "/debug/pprof", "/env", "/info", "/dump",
		"/robots.txt", "/sitemap.xml", "/crossdomain.xml",
		"/server-status", "/server-info",
		"/.git/HEAD", "/.env", "/config.json", "/package.json",
	}
}
